### ISSUE TITLE
remote-write-receiver flag syntax changed

### ISSUE THREAD

**Issue by danatsk** [mmanningcp/skylineinstructions#3]
Hey,
please notice that the syntax of Prometheus feature flags changed (to reference: [official Prometheus instructions](https://prometheus.io/docs/prometheus/latest/feature_flags/))
and when starting up the server, the command should be
sudo prometheus --enable.feature=remote-write-receiver

p.s
it would be great if you could add a reference to the official Checkpoint guide for Skyline deployment (could be found here: [Skyline Deployment](https://support.checkpoint.com/results/sk/sk178566)

**Comment by JanBaudis** [comment]
I think the currently used argument is correct. The one you provided is the old one when it was only a feature flag. And if i dont misunderstand the guide the arg via the feature flag is deprecated.

**Comment by PinguOfTheNoot** [comment]
> I think the currently used argument is correct. The one you provided is the old one when it was only a feature flag. And if i dont misunderstand the guide the arg via the feature flag is deprecated.

+1
