### ISSUE TITLE
Instruction are wrong in regards of the write-receiver when used with systemd

### ISSUE THREAD

**Issue by JanBaudis** [mmanningcp/skylineinstructions#4]
Thanks for your guide.
Unfortunately there is an error in your guide regarding enabling the write receiver via systemd. The setting in the yml _remote_write_ is used for sending/writing data to that endpoint. This is different from the write receiver. See: https://prometheus.io/docs/prometheus/latest/storage/#overview
One way to enable this in the systemd file is to append the "--web.enable-remote-write-receiver" flag to ExecStart.

Best regards
Jan

**Comment by PinguOfTheNoot** [comment]
> Thanks for your guide. Unfortunately there is an error in your guide regarding enabling the write receiver via systemd. The setting in the yml _remote_write_ is used for sending/writing data to that endpoint. This is different from the write receiver. See: https://prometheus.io/docs/prometheus/latest/storage/#overview One way to enable this in the systemd file is to append the "--web.enable-remote-write-receiver" flag to ExecStart.
> 
> Best regards Jan

Hi Jan, I agree. I used the line below to get it to work for me under /etc/systemd/system/prometheus.service
`ExecStart=/home/ben/prometheus-2.38.0.linux-amd64/prometheus --config.file=/home/ben/prometheus-2.38.0.linux-amd64/prometheus.yml --web.enable-remote-write-receiver`

**Comment by mmanningcp** [comment]
Thank you. I've updated the document
